config/routes.rb
Rails.application.routes.draw do

# AdminUser 用の Devise ルーティング
devise_for :admin_users, controllers: {
  sessions: 'admin_users/sessions',
  registrations: 'admin_users/registrations',
}

# User 用の Devise ルーティング
devise_for :users, controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations',
}


  

  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  
  root "shifts#index"

  resources :shifts, only: [:index, :create, :edit]
  resources :calendar, only: [:index, :edit, :update]
  resources :shift_settings, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :employees, only: [:index, :new, :create, :edit, :update, :destroy]

  

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
    before_action :authenticate_admin_user!
    before_action :set_employee, only: [:edit, :update, :destroy]


     # 従業員の一覧表示
    def index
      @employees =User.all
    end
    # 新しい従業員を作成するためのフォームを表示
    def new
        @employee = User.new
    end
    # 新しい従業員を保存
    def create
        @employee = User.new(employee_params)
        if @employee.save
          redirect_to employees_path, notice: '従業員を追加しました'
        else
          render :new
        end
    end

     # 従業員の編集フォームを表示
    def edit
    end

     # 従業員の編集フォームを表示
    def update
        if @employee.update(employee_params)
          redirect_to employees_path, notice: 'シフト設定が更新されました。'
        else
          render :edit
        end
    end


    # 従業員を削除
    def destroy
        @employee.destroy
        redirect_to employees_path, notice: 'シフト設定が削除されました。'
    end

    private

    # 従業員IDを取得
    def set_employee
        @employee = User.find(params[:id])
      
    end
    
    def employee_params
        params.require(:user).permit(:employee_id, :email, :password, :password_confirmation, :name)
    end


end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/edit.html.erb
<div class="container">
  <ul class="admin-nav-bar">
        <% if admin_user_signed_in? %>
          <li><%= link_to "従業員一覧", employees_path %></li>
          <li><%= link_to 'シフト設定一覧', shift_settings_path %></li>
          <li><%= link_to 'シフト一覧', root_path %></li>
          <li class="logout-btn"><%= link_to "ログアウト", destroy_admin_user_session_path, data: { turbo_method: :delete } %></li>
        <% else %>
          <li><%= link_to "新規登録", new_admin_user_registration_path %></li>
          <li><%= link_to "ログイン", new_admin_user_session_path %></li>
        <% end %>
    </ul>


  <h1 class="ttl">従業員の編集</h1>

  <%= form_with model: @employee, url: employees_path do |form| %>
    <div class="field">
      <%= form.label :email %><br />
      <%= form.email_field :email, autofocus: true, autocomplete: "email" %>
    </div>
    <div class="field">
      <%= form.label :name, "従業員名"%><br />
      <%= form.text_field :name, autofocus: true, autocomplete: "name" %>
    </div>
    <div class="field">
      <%= form.label :employee_id, "従業員ID"%><br />
      <%= form.text_field :employee_id, autofocus: true, autocomplete: "employee_id" %>
    </div>

    <div class="field">
      <%= form.label :password %>
      <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br />
      <%= form.password_field :password, autocomplete: "new-password" %>
    </div>

    <div class="field">
      <%= form.label :password_confirmation %><br />
      <%= form.password_field :password_confirmation, autocomplete: "new-password" %>
    </div>

    <div >
      <%= form.submit '変更する',class:"submit-button"%>
    </div>
  <% end %>
</div>

app/views/employees/index.html.erb
<div class="container">
  <ul class="admin-nav-bar">
        <% if admin_user_signed_in? %>
          <li><%= link_to "従業員一覧", employees_path %></li>
          <li><%= link_to 'シフト設定一覧', shift_settings_path %></li>
          <li><%= link_to 'シフト一覧', root_path %></li>
          <li class="logout-btn"><%= link_to "ログアウト", destroy_admin_user_session_path, data: { turbo_method: :delete } %></li>
        <% else %>
          <li><%= link_to "新規登録", new_admin_user_registration_path %></li>
          <li><%= link_to "ログイン", new_admin_user_session_path %></li>
        <% end %>
    </ul>

  <h1 class="ttl">従業員一覧</h1>

  <%= link_to '従業員の追加', new_employee_path ,class: "create-btn" %>
  <div class="main-space">
  <table class="employee-table">
    <thead>
      <tr>
        <th>名前</th>
        <th>メールアドレス</th>
        <th>従業員ID</th>
        <th>アクション</th>
      </tr>
    </thead>
    <tbody>
      <% @employees.each do |employee| %>
        <tr>
          <td><%= employee.name %></td>
          <td><%= employee.email %></td>
          <td><%= employee.employee_id %></td>
          <td>
            <%= link_to '編集', edit_employee_path(employee), class: "btn btn-edit" %>
            <%= link_to '削除', employee_path(employee), data: { turbo_method: :delete }, class: "btn btn-delete" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/employees/new.html.erb
<div class="container">
  <ul class="admin-nav-bar">
        <% if admin_user_signed_in? %>
          <li><%= link_to "従業員一覧", employees_path %></li>
          <li><%= link_to 'シフト設定一覧', shift_settings_path %></li>
          <li><%= link_to 'シフト一覧', root_path %></li>
          <li class="logout-btn"><%= link_to "ログアウト", destroy_admin_user_session_path, data: { turbo_method: :delete } %></li>
        <% else %>
          <li><%= link_to "新規登録", new_admin_user_registration_path %></li>
          <li><%= link_to "ログイン", new_admin_user_session_path %></li>
        <% end %>
    </ul>


  <h1 class="ttl">従業員の追加</h1>

  <%= form_with model: @employee, url: employees_path do |form| %>
    <div class="field">
      <%= form.label :email %><br />
      <%= form.email_field :email, autofocus: true, autocomplete: "email" %>
    </div>
    <div class="field">
      <%= form.label :name, "従業員名"%><br />
      <%= form.text_field :name, autofocus: true, autocomplete: "name" %>
    </div>
    <div class="field">
      <%= form.label :employee_id, "従業員ID"%><br />
      <%= form.text_field :employee_id, autofocus: true, autocomplete: "employee_id" %>
    </div>

    <div class="field">
      <%= form.label :password %>
      <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br />
      <%= form.password_field :password, autocomplete: "new-password" %>
    </div>

    <div class="field">
      <%= form.label :password_confirmation %><br />
      <%= form.password_field :password_confirmation, autocomplete: "new-password" %>
    </div>

    <div class="actions">
      <%= form.submit '追加' %>
    </div>
  <% end %>
</div>