config/routes.rb
Rails.application.routes.draw do

# AdminUser 用の Devise ルーティング
devise_for :admin_users, controllers: {
  sessions: 'admin_users/sessions',
  registrations: 'admin_users/registrations',
}

# User 用の Devise ルーティング
devise_for :users, controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations',
}


  

  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  
  root "shifts#index"

  resources :shifts, only: [:index, :create, :edit]
  resources :calendar, only: [:index, :edit, :update]
  resources :shift_settings, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :employees, only: [:index, :new, :create, :edit, :update, :destroy]

  

end

app/models/shift_setting.rb
class ShiftSetting < ApplicationRecord
  before_create :set_default_name

  belongs_to :admin_user
  has_many :shift_requests
  has_many :shifts
  has_many :users, through: :shift_requests

  validates :send_date, presence: true
  validates :deadline_date, presence: true
  validates :remind_date, presence: true

# メール送信メソッド
    def send_emails
      users = User.all 
      users.each do |user|
        ShiftMailer.shift_request(user, self).deliver_now
      end
    end

# リマインドメール送信メソッド
    def send_reminder_emails
      users = User.all 
      users.each do |user|
        ShiftMailer.shift_request_reminder(user, self).deliver_now
      end
    end

    # シフトリクエストインスタンスを作成
    def self.create_shift_requests(shift_setting)
         users = User.all
         users.each do |user|
          ShiftRequest.create(user: user, shift_setting: shift_setting)
        end
    end
  
    
    # wheneverで実行されるメソッド
    def self.check_shift
      ShiftSetting.find_each do |shift_setting|
        # シフト設定の送信日担ったらシフトリクエスト作成メソッドを呼び出す
        if shift_setting.send_date==Date.today.day
          ShiftSetting.create_shift_requests(shift_setting)
        end
         # シフト設定の締め切り日を過ぎたら、シフト作成メソッドを呼び出す
        if shift_setting.deadline_date<Date.today.day
          WorkShift.create_shift_assignments()
        end
        # シフト設定の締め切り日を過ぎたら、シフトリクエストを消す
        if Date.today.day > shift_setting.deadline_date
          shift_setting.shift_requests.destroy_all
        end
      end
    end

  private


# シフト設定の名前生成
  def set_default_name
    if self.name.blank?
      current_count = ShiftSetting.count + 1
      self.name = "シフト設定-#{current_count}"
    end 
  end 
end  

app/controllers/shift_settings_controller.rb
class ShiftSettingsController < ApplicationController
    before_action :authenticate_admin_user!
    before_action :set_shift_setting, only: [:edit, :update, :destroy]
  
    # シフト設定の一覧表示
    def index
      @shift_settings = ShiftSetting.all
    end
  
    # 新しいシフト設定を作成するためのフォームを表示
    def new
      @shift_setting = ShiftSetting.new
    end
  
    # 新しいシフト設定を保存
    def create
      @shift_setting = ShiftSetting.new(shift_setting_params)
      @shift_setting.admin_user = current_admin_user
      Rails.logger.debug("Current admin user: #{current_admin_user.inspect}")

      if @shift_setting.save
        Rails.logger.debug("設定された名前: #{@shift_setting.name}")
        redirect_to shift_settings_path, notice: 'シフト設定が作成されました。'
        
      else
        Rails.logger.debug("エラー内容: #{@shift_setting.errors.full_messages}")
        render :new
      end
    end
  
    # シフト設定の編集フォームを表示
    def edit
    end
  
   # シフト設定の編集フォームを表示
    def update
      if @shift_setting.update(shift_setting_params)
        redirect_to shift_settings_path, notice: 'シフト設定が更新されました。'
      else
        render :edit
      end
    end
  
    # シフト設定を削除
    def destroy
      @shift_setting.destroy
      redirect_to shift_settings_path, notice: 'シフト設定が削除されました。'
    end
  
    private

    # シフト設定IDを取得
    def set_shift_setting
      @shift_setting = ShiftSetting.find(params[:id])
    end
  
    def shift_setting_params
      params.require(:shift_setting).permit(:send_date, :deadline_date, :remind_date)
    end
  end
  

app/helpers/shift_settings_helper.rb
module ShiftSettingsHelper
end

app/views/shift_settings/edit.html.erb
<div class="container">
  <ul class="admin-nav-bar">
          <% if admin_user_signed_in? %>
            <li><%= link_to "従業員一覧", employees_path %></li>
            <li><%= link_to 'シフト設定一覧', shift_settings_path %></li>
            <li><%= link_to 'シフト一覧', root_path %></li>
            <li class="logout-btn"><%= link_to "ログアウト", destroy_admin_user_session_path, data: { turbo_method: :delete } %></li>
          <% else %>
            <li><%= link_to "新規登録", new_admin_user_registration_path %></li>
            <li><%= link_to "ログイン", new_admin_user_session_path %></li>
          <% end %>
      </ul>

  <h1 class="ttl">シフト設定を編集</h1>

  <%= form_with model: @shift_setting do |form| %>
    <div class="field">
      <%= form.label :send_date, "シフト希望送信日" , class: "field-label" %>
      <%= form.number_field :send_date, min: 1, max: 31, required: true, class: "field-input"  %> 
    </div>

    <div class="field">
      <%= form.label :deadline_date, "提出期限の日", class: "field-label"  %>
      <%= form.number_field :deadline_date, min: 1, max: 31, required: true, class: "field-input"  %>
    </div>

    <div class="field">
      <%= form.label :remind_date, "リマインド日", class: "field-label"  %>
      <%= form.number_field :remind_date, min: 1, max: 31, required: true, class: "field-input"  %>
    </div>

    <div>
      <%= form.submit '更新' ,class: "submit-button" %>
    </div>
  <% end %>

</div>

app/views/shift_settings/index.html.erb
<div class="container">
  <ul class="admin-nav-bar">
      <% if admin_user_signed_in? %>
        <li><%= link_to "従業員一覧", employees_path %></li>
        <li><%= link_to 'シフト設定一覧', shift_settings_path %></li>
        <li><%= link_to 'シフト一覧', root_path %></li>
        <li class="logout-btn"><%= link_to "ログアウト", destroy_admin_user_session_path, data: { turbo_method: :delete } %></li>
      <% else %>
        <li><%= link_to "新規登録", new_admin_user_registration_path %></li>
        <li><%= link_to "ログイン", new_admin_user_session_path %></li>
      <% end %>
  </ul>

  <h1 class="ttl">シフト設定一覧</h1>
   <%= link_to '新しいシフト設定を作成', new_shift_setting_path, class: "create-btn" %>

  <div class="main-space">  

    <div class="shift-cards">
  <% @shift_settings.each do |setting| %>
    <div class="shift-card">
      <div class="shift-ttl">
        <%= setting.name %>
      </div>
      <div class="shift-body">
        <p><strong>送信日:</strong> <%= setting.send_date %></p>
        <p><strong>リマインダー日:</strong> <%= setting.remind_date %></p>
        <p><strong>締め切り日:</strong> <%= setting.deadline_date %></p>
      </div>
      <div class="shift-actions">
          <%= link_to '編集', edit_shift_setting_path(setting), class: "btn-edit" %>
          <%= link_to '削除', shift_setting_path(setting), data: { turbo_method: :delete },class: "btn-delete" %>
    </div>
    </div>
  <% end %>
</div>
  </div>

</div>

app/views/shift_settings/new.html.erb
<div class="container">
  <ul class="admin-nav-bar">
        <% if admin_user_signed_in? %>
          <li><%= link_to "従業員一覧", employees_path %></li>
          <li><%= link_to 'シフト設定一覧', shift_settings_path %></li>
          <li><%= link_to 'シフト一覧', root_path %></li>
          <li class="logout-btn"><%= link_to "ログアウト", destroy_admin_user_session_path, data: { turbo_method: :delete } %></li>
        <% else %>
          <li><%= link_to "新規登録", new_admin_user_registration_path %></li>
          <li><%= link_to "ログイン", new_admin_user_session_path %></li>
        <% end %>
    </ul>


  <h1 class="ttl">新しいシフト設定を作成</h1>

  <%= form_with(model: @shift_setting, local: true) do |form| %>

    <% if @shift_setting.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@shift_setting.errors.count, "エラー") %> が発生しました:</h2>
        <ul>
          <% @shift_setting.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>


    <div class="field">
      <%= form.label :send_date, "シフト希望送信日" , class: "field-label" %>
      <%= form.number_field :send_date, min: 1, max: 31, required: true, class: "field-input"  %> 
    </div>

    <div class="field">
      <%= form.label :deadline_date, "提出期限の日", class: "field-label"  %>
      <%= form.number_field :deadline_date, min: 1, max: 31, required: true, class: "field-input"  %>
    </div>

    <div class="field">
      <%= form.label :remind_date, "リマインド日", class: "field-label"  %>
      <%= form.number_field :remind_date, min: 1, max: 31, required: true, class: "field-input"  %>
    </div>

    <div class="actions">
      <%= form.submit  '作成する' %>
    </div>
  <% end %>

</div>